# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
# home assistant python base images don't work due to error with ninja dependency of scikit-learn
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-debian:latest"
  amd64: "ghcr.io/home-assistant/amd64-base-debian:latest"
#  armhf: "ghcr.io/home-assistant/armhf-base-debian:latest"
#  armv7: "ghcr.io/home-assistant/armv7-base-debian:latest"
#  i386: "ghcr.io/home-assistant/i386-base-debian:latest"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: EOS add-on"
  org.opencontainers.image.description: "Energy Optimization System add-on for home assistant."
  org.opencontainers.image.source: "https://github.com/Duetting/ha_eos_addon"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
