build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.13-alpine3.22"
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.13-alpine3.22"
  # armhf: "ghcr.io/home-assistant/armhf-base-python:3.11-alpine3.22"
  # armv7: "ghcr.io/home-assistant/armv7-base-python:3.11-alpine3.22"
  # i386: "ghcr.io/home-assistant/i386-base-python:3.11-alpine3.22"

args:
  TEMPIO_VERSION: "2021.09.0"

labels:
  org.opencontainers.image.title: "EOS Connect"
  org.opencontainers.image.description: "EOS Connect Add-on"
  org.opencontainers.image.source: "https://github.com/ohAnd/ha_addons"
  org.opencontainers.image.authors: "ohAnd"
  org.opencontainers.image.licenses: "MIT"
