name: "Batcontrol - Dev@ohAnd"
description: "Controls the charging of the battery"
version: "0.3.5"
slug: "batcontrol"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - type: ssl
  - type: addon_config
    read_only: false
    path: /app/addon_config

options:
  timezone: Europe/Berlin #your time zone. not optional.
  loglevel: debug
  max_logfile_size: 100 #kB
  battery_control:
    min_price_difference: 0.05 # minimum price difference in Euro to justify charging your battery
    always_allow_discharge_limit: 0.90 # 0.00 to 1.00 above this SOC limit using energy from the battery is always allowed
    max_charging_from_grid_limit: 0.90 # 0.00 to 1.00 charging from the grid is only allowed until this SOC limit
  inverter:
    type: fronius_gen24 #currently only fronius_gen24 supported
    address: 192.168.0.XX # the local IP of your inverter. needs to be reachable from the machine that runs batcontrol
    user: customer #customer or technician lowercase only!!
    password: YOUR-PASSWORD #
    max_pv_charge_rate: 3000 # Watt
    max_grid_charge_rate: 5000 # Watt
    max_bat_discharge_rate: 5000 # Watt - set to 0 to disable
  utility:
    type: tibber
    apikey: Zz-YOURAPIKEYYOURAPIKEYXXXXX # only required for tibber
    vat: 0.20 # only required for awattar
    fees: 0.015 # only required for awattar
    markup: 0.03 # only required for awattar
  pvinstallations:
    - name: Haus #name
      lat: 48.4334480
      lon: 8.7654968
      declination: 32 #inclination toward horizon 0..90 0=flat 90=vertical (e.g. wallmounted)
      azimuth: -90 # -90:East, 0:South, 90:West -180..180
      kWp: 15.695 # power in kWp
  consumption_forecast:
    annual_consumption: 4500 # total consumption in kWh p.a. the load profile
    load_profile: load_profile.csv #name of the load profile file within the config folder
  mqtt:
    enabled: false
    logger: false
    broker: core-mosquitto
    port: 1883
    topic: house/batcontrol
    username: user
    password: password
    tls: false
    cafile: /ssl/certs/ca-certificates.crt
    certfile: /ssl/certs/client.crt
    keyfile: /ssl/certs/client.key
    tls_version: tlsv1.2
  evcc:
    enabled: false
    broker: core-mosquitto
    port: 1883
    status_topic: evcc/status
    # one loadpoints that should be monitored
    loadpoint_topic:
      - evcc/loadpoints/1/charging
    username: user
    password: password
    tls: false
    cafile: /ssl/certs/ca-certificates.crt
    certfile: /ssl/certs/client.crt
    keyfile: /ssl/certs/client.key
    tls_version: tlsv1.2
schema:
  timezone: str #your time zone. not optional.
  loglevel: list(debug|info|warning|error)
  max_logfile_size: int
  battery_control:
    min_price_difference: float(0,) # minimum price difference in Euro to justify charging your battery
    always_allow_discharge_limit: float(0,1) # 0.00 to 1.00 above this SOC limit using energy from the battery is always allowed
    max_charging_from_grid_limit: float(0,1) # 0.00 to 1.00 charging from the grid is only allowed until this SOC limit
  inverter:
    type: list(fronius_gen24) #currently only fronius_gen24 supported
    address: str # the local IP of your inverter. needs to be reachable from the machine that runs batcontrol
    user: list(customer|technician) #customer or technician lowercase only!!
    password: password
    max_pv_charge_rate: float(0,)?
    max_grid_charge_rate: float(0,)?
  utility:
    type: list(tibber|awattar_at|awattar_de)
    apikey: password? # only required for tibber
    vat: float(0,10)? # only required for awattar
    fees: float(0,10)? # only required for awattar
    markup: float(0,10)? # only required for awattar
  pvinstallations:
    - name: str #name
      lat: float(,90)
      lon: float(,90)
      declination: float(0,90) #inclination toward horizon 0..90 0=flat 90=vertical (e.g. wallmounted)
      azimuth: float(,180) # -90:East, 0:South, 90:West -180..180
      kWp: float(0,) # power in kWp
      apikey: str? #forecastsolarapi
  consumption_forecast:
    annual_consumption: float(0,)? # total consumption in kWh p.a. the load profile
    load_profile: str #name of the load profile file within the config folder
  mqtt:
    enabled: bool
    logger: bool
    broker: str
    port: int
    topic: str
    username: str?
    password: password?
    tls: bool
    cafile: str?
    certfile: str?
    keyfile: str?
    tls_version: list(tlsv1.2|tlsv1.3)?
  evcc:
    enabled: bool
    broker: str
    port: int
    status_topic: str
    # one loadpoints that should be monitored
    loadpoint_topic:
      - str
    username: str?
    password: str?
    tls: bool
    cafile: str?
    certfile: str?
    keyfile: str?
    tls_version: list(tlsv1.2|tlsv1.3)?
